CREATE OR REPLACE DATABASE LIQUIDRADAR;

CREATE OR REPLACE SCHEMA LIQUIDRADAR.TRADE;

CREATE OR REPLACE TABLE LIQUIDRADAR.TRADE.COINBASE_TRADE_BTCUSD_RAW (
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT
);

ALTER USER YOUR_SNOWFLAKE_USER SET RSA_PUBLIC_KEY='YOUR_SNOWFLAKE_KEY';
